---
format: 
  pdf: 
    papersize: letter
    documentclass: article
    lang: es-CR
    titlepage: true
    toc: false
    toccolor: "black"
    fontsize: "11pt"
    mainfont: Times New Roman
    urlcolor: "blue"
    number-sections: false
    margin-left: "2.54cm"
    margin-right: "2.54cm"
    margin-top: "2.54cm"
    margin-bottom: "2.54cm"
    header-includes:
      - \usepackage{indentfirst}
      - \setlength{\parindent}{1.27cm}
      - \usepackage{longtable}
      - \usepackage{array}
      - \renewcommand{\arraystretch}{1.5}
      - \setlength{\tabcolsep}{8pt}
      - \usepackage{setspace}
      - \usepackage{booktabs}
      - \usepackage{float}
      - \setstretch{1.15}
editor: 
  markdown: 
    wrap: sentence
---


```{=latex}
\begin{center}
```

```{=latex}
{\fontsize{16pt}{14pt}\selectfont\textbf{Informe del proyecto grupal: CA0305}}
```

```{=latex}
{\fontsize{12pt}{14pt}\selectfont Alexandra González, Estefanía Mora, Daniela Prado, Liz Salazar y Ericka Wu}
```

```{=latex}
\end{center}
```


# Introducción

# Datos y análisis

La selección de la base de datos a partir de la cual se desarrollará un proyecto, constituye uno de los elementos de mayor importancia en el proceso. Por ello, es fundamental conocer en detalle las características del conjunto de datos elegido, incluyendo su origen, sus autores, la cantidad de observaciones disponibles y otros elementos relevantes. Bajo el contexto planteado, la presente sección está destinada a describir el conjunto de datos utilizado en el proyecto.

## Descripción de la base de datos

La base de datos empleada en el proyecto se denomina *Caltech 101*. Corresponde a un conjunto de datos de imágenes digitales recopiladas en setiembre de 2003 por los investigadores Fei-Fei Li, Marco Andreetto, Marc'Aurelio Ranzato y Pietro Perona, en el Instituto Tecnológico de California en Estados Unidos. El principal objetivo de los investigadores consistía en facilitar la investigación en el campo de la visión artificial, además de brindar una herramienta útil tanto para la categorización como para la clasificación de las imágenes. 

Por otro lado, de acuerdo con Griffin et al. (2007), el proceso de construcción de la base de datos respondió al siguiente procedimiento: en un primer momento, se definió un conjunto de categorías de objetos, después, en un segundo momento, se extrajo una serie de imágenes de Internet utilizando el buscador de Google Imágenes, finalmente, en un tercer momento, se filtró manualmente los resultados en vías de eliminar todas las imágenes que no se ajustaban de forma correcta a la categoría asignada.


## Análisis de la base de datos

# Método y resultados

## Descripción del modelo

El modelo escogido Vit-Base es una arquitectura de aprendizaje profundo diseñada para la clasificación de imágenes. A diferencia de redes convolucionales tradicionales, Vit adapta la arquitectura Transformer (originalmente creada para analizar lenguaje natural) al análisis de imágenes. 

Primero, redimensiona la imagen  a 224×224 píxeles  y luego la divide en 196 parches de 16×16 píxeles , característico de la variante Vit-Base/16. Cada parche se transforma en un vector numérico mediante una proyección lineal, de esta forma se obtiene una secuencia de representaciones. Mediante esta secuencia, se le incorpora información de la posición inicial de cada parche, ya que al convertirlos en una lista lineal se pierde la información de que parches eran vecinos en la imagen original, de esta forma, se podrá conocer la disposición espacial de cada elemento y permitir relacionarlos entre sí.

La secuencia completa pasa por una serie de bloques Transformer, cada uno compuesto por un mecanismo de atención y capas de transformación. El mecanismo de atención permite que cada parche intercambie información con los demás, independientemente de su distancia en la imagen. 

Adicionalmente, se añade un token al inicio de la secuencia, el cual, tras el procesamiento, concentra la información de toda la imagen. Se considera el puente que ayuda al modelo a transformar este vector numérico a las categorías que tenga el dataset, además, al pasar ese vector por una función matemática llamada softmax, cada categoría se transforma en una probabilidad donde todas suman 1. Finalmente, el modelo muestra la categoría con mayor probabilidad de que la imagen pertenezca a ella.

## Relación con la fundamentación matemática de las bitácoras

La confianza representa el grado de certeza con que el modelo asigna una categoría a cada imagen analizada. Un valor alto indica que el modelo identificó características visuales consistentes con una categoría específica; un valor bajo sugiere que la imagen no presenta similitudes claras con ninguna de las categorías conocidas por el modelo. La confianza se genera mediante la función softmax, mencionada anteriormente, que transforma la información generada por el token especial a probabilidades mediante una distribución válida. 


## Resultados 

Para la generación de resultados, se aplicó el modelo al dataset escogido: *Caltech 101* a las primeras 100 imágenes, con el fin de encontrar una conclusión acerca de cómo funciona el modelo y sus limitaciones. Primero, al analizar la coincidencia de las etiquetas del dataset Caltech-101 respecto a las predicciones del modelo entrenado en ImageNet, se encontró que solo el 7% coincide en texto exacto. Sin embargo, el modelo ha logrado acertar categorías que se parezcan o esten relacionadas con las etiquetas de los datos analizados como por ejemplo airplanes con airliner. Además, los casos con mayor confianza tienden a coincidir semánticamente con la etiqueta real, como se muestra en la siguiente tabla.

\begin{table}[H]
    \centering
    \caption{Predicciones con mayor confianza del modelo ViT-Base}
    \begin{tabular}{cllr}
        \toprule
        Imagen & Clase real & Predicción del modelo & Confianza \\
        \midrule
        36 & nautilus & chambered nautilus, pearly nautilus & 0.999 \\
        52 & trilobite & trilobite & 0.999 \\
        96 & accordion & accordion, piano accordion & 0.999 \\
        90 & binocular & binoculars, field glasses & 0.999 \\
        17 & flamingo\_head & flamingo & 0.999 \\
        51 & flamingo & flamingo & 0.998 \\
        31 & scorpion & scorpion & 0.998 \\
        73 & revolver & revolver, six-gun & 0.998 \\
        35 & beaver & beaver & 0.997 \\
        69 & airplanes & airliner & 0.997 \\
        \bottomrule
    \end{tabular}
    \label{tab:mayor_confianza}
\end{table}

En el histograma siguiente se muestra la distribución de la confianza asignada a las 100 imágenes analizadas. Un 30% de las imágenes obtuvo una confianza cercana a 1.0, lo que corresponde a los casos en que la predicción del modelo tiende a coincidir semánticamente con la etiqueta real del dataset (por ejemplo, "airliner" para imágenes etiquetadas como "airplanes"). Las imágenes restantes presentan una distribución dispersa a lo largo del rango de confianza, lo que indica menor certeza en la clasificación. La confianza promedio obtenida fue de 61.3%, lo que sugiere un desempeño moderado del modelo sobre este dataset.



# Conclusiones

# Referencias
\begin{list}{}{
\setlength{\leftmargin}{1.27cm}
\setlength{\itemindent}{-1.27cm}
}

\item Griffin, G., Holub, H. \& Perona, P. (2007). \textit{Caltech-256 Object Category Dataset}. ResearchGate. \url{https://www.researchgate.net/publication/30766223_Caltech-256_Object_Category_Dataset}\par
\vspace{0.03cm}

\item Li, F., Andreeto, M., Ranzato, M. \& Perona, P. (2022). \textit{Caltech 101 (1.0)} [Data set]. CaltechDATA. \url{https://doi.org/10.22002/D1.20086}\par
\vspace{0.03cm}

\end{list}